---
  #- name: "Add Node.js from Nodesource"
    #become: true
    #shell: |
      #curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

  #- name: "install nodejs"
    #become: true
    #apt: 
      #name: nodejs
      #state: present
      #update_cache: yes

  #- name: "check node.js Version"
    #become: true
    #shell: |
      #node -v
  
  #- name: "install pm2"
    #become: true
    #shell: |
      #node -v
      #npm --version
      #npm install pm2 -g

  ###################

  - name: "Update apt packages"
    become: true
    apt:
      update_cache: yes

  - name: "Remove dependencies that are no longer required"
    become: true
    apt:
      autoremove: yes

  - name: "Install npm and nodejs"
    become: true
    apt:
      name: ["npm", "nodejs"]
      state: latest
      update_cache: yes

  - name: "Install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

