---
  
  - name: "install dependencies."
    apt: 
      name: npm
      update_cache: yes

  - name: "install pm2"
    become: true
    npm: 
      name: pm2
      global: yes
      production: yes
      state: present