---
  - name: "Creates backend app directory"
    file:
      path: ~/backend-app
      state: directory

  - name: "Artifact extration"
    unarchive:
      src: artifact.tar.gz
      dest: ~/backend-app

  - name: "Installing Node Dependencies"
    shell: |
      cd ~/backend-app
      npm i

  - name: Start The Application
    become: true
    shell: |
      npm install
      pm2 stop default
      pm2 start npm -- start
    