---

  - name: "Artifact extration"
    unarchive:
      src: artifact.tar.gz
      dest: .

  - name: start app
    become: true
    shell: |

      npm install
      pm2 stop default
      pm2 start npm -- start
      #pm2 start main.js
    register: execute_node

  - name: print message
    debug:
      msg: "{{ execute_node.stdout_lines }}"
    