---
  - name: Artifact extration
    become: true
    unarchive: 
      src: artifact.tar.gz
      dest: .

  - name: Start The Application
    become: true
    shell: |
      npm install
      pm2 stop default
      pm2 start npm -- start
    