---

  - name: "Artifact extration"
    unarchive:
      src: artifact.tar.gz
      dest: .
  - name: "Installing Node Dependencies"
    shell: |
      npm install

  - name: start app
    become: true
    shell: |
      ls
      cd ~/dist
      pm2 stop default
      #pm2 start main.js
      pm2 start npm -- start
    register: execute_node

  - name: print message
    debug:
      msg: "{{ execute_node.stdout_lines }}"
    